### ISSUE TITLE
Remove styling

### ISSUE THREAD

**Issue by Hesesses** [bumpcore/editor.php#67]
Hello,

I'm trying to use this package and noticed that rendering blocks adds styling, for example:
```<p class="text-base mb-4 [&amp;>a]:text-blue-600 [&amp;>a]:underline hover:[&amp;>a]:text-blue-400 [&amp;>code]:text-red-500 [&amp;>code]:bg-red-100 [&amp;>code]:px-1 [&amp;>code]:rounded-md [&amp;>code]:whitespace-nowrap [&amp;>code]:font-medium [&amp;>mark]:bg-yellow-200">My content</p>```

Instead of: 
```<p>My content</p>```

Am I missing something, or is this doable without extending / modifying each block?

**Comment by Hesesses** [comment]
Related to this, would be nice to be able to publish current block blade files to make modifications directly to those

**Comment by megasteve19** [comment]
Hi there! Thank you very much for your feedback.

Regarding to styles, there's support for both Bootstrap 5 and tailwindcss. By the default tailwind templates are being used. Sadly, there's no template with no styling.  But it is possible to publish view files with `vendor:publish` command;

```bash
php artisan vendor:publish --tag=editor.php
```

It will publish both views and config, with published views you may adjust the stylings according to your desires.
